"
! Migrations

The difficulty of doing migrations well is often underestimated. At first sight they look straightforward, not too difficult and easy to plan. However, in most cases the preconditions to do a  migration as a complicated project (in cynefin terms) are not met. An approach based on a fast feedback cycle with daily visualizations and the incremental development of an idealized migration model can be much more successfull

!! Preconditions

For a migration to be plannable, there needs to be sufficient knowledge available on all relevant aspects of the migration. This includes 
- knowledge of the old system 
- knowledge of the new system 
- knowledge of migrations
Common problems with this are:
- insufficient knowledge of the old system. 
- no interest in success for the maintainers of the old system 
- underestimation of the migration scope 
- technical debt in the old system 
- too many intermediates in the communication for effective decision making

!! Daily visualizations

!! An idealized migration model  

"
Class {
	#name : #Migrations,
	#superclass : #Object,
	#category : #Migrations
}
