"
! Migrations

The difficulty of doing migrations well is often underestimated. At first sight they look straightforward, not too difficult and easy to plan. However, in most cases the preconditions to do a  migration as a complicated project (in cynefin terms) are not met. An approach based on a fast feedback cycle with daily visualizations and the incremental development of an idealized migration model can be much more successfull

!! Preconditions

!! Daily visualizations

!! An idealized migration model  

"
Class {
	#name : #Migrations,
	#superclass : #Object,
	#category : #Migrations
}
